### ISSUE TITLE
Repeated values in class names

### ISSUE THREAD

**Issue by ilariaventurini** [svg/svgo#1133]
Use `--multipass` option and `{"prefixIds":true}` creates css class names with repeated values.
For example run `svgo hello3.svg -o - --pretty --config='{"plugins":[{"prefixIds":true}]}' --multipass` using the svg file `hello3.svg`:

    <svg xmlns="http://www.w3.org/2000/svg" id="Livello_1" data-name="Livello 1" viewBox="0 0 300 170">
      <style>
        .cls-1{fill:#d9e7f2;}.cls-2{fill:#1191ae;}
      </style>
      <rect width="265.1" height="1" x="32.9" y="117.95" class="cls-1"/>
      <rect width="265.1" height="1" x="32.9" y="90.08" class="cls-1"/>
      <rect width="265.1" height="1" x="32.9" y="61.68" class="cls-1"/>
      <rect width="265.1" height="1" x="32.9" y="33.8" class="cls-1"/>
      <rect width="266.03" height="1" x="32.4" y="5.4" class="cls-1"/>
      <rect width="15.12" height="27.88" x="54.66" y="118.5" class="cls-2"/>
      <rect width="15.12" height="39.97" x="89.49" y="106.4" class="cls-2"/>
      <rect width="15.12" height="80.47" x="124.33" y="65.91" class="cls-2"/>
      <rect width="15.12" height="98.35" x="159.16" y="48.02" class="cls-2"/>
      <rect width="15.12" height="83.1" x="193.99" y="63.28" class="cls-2"/>
      <rect width="15.12" height="108.87" x="228.83" y="37.51" class="cls-2"/>
      <rect width="15.12" height="30.5" x="263.66" y="115.87" class="cls-2"/>
      <rect width="266.03" height="1" x="32.4" y="145.83" class="cls-1"/>
    </svg>

Creates this svg:

    <svg xmlns="http://www.w3.org/2000/svg" id="hello3_svg__hello3_svg__hello3_svg__Livello_1" data-name="Livello 1" viewBox="0 0 300 170">
        <style>
            .hello3_svg__hello3_svg__hello3_svg__cls-1{fill:#d9e7f2}
        </style>
        <path class="hello3_svg__hello3_svg__hello3_svg__cls-1" d="M32.9 117.95H298v1H32.9zm0-27.87H298v1H32.9zm0-28.4H298v1H32.9zm0-27.88H298v1H32.9zm-.5-28.4h266.03v1H32.4z"/>
        <path d="M54.66 118.5h15.12v27.88H54.66zm34.83-12.1h15.12v39.97H89.49zm34.84-40.49h15.12v80.47h-15.12zm34.83-17.89h15.12v98.35h-15.12zm34.83 15.26h15.12v83.1h-15.12zm34.84-25.77h15.12v108.87h-15.12zm34.83 78.36h15.12v30.5h-15.12z" fill="#1191ae"/>
        <path class="hello3_svg__hello3_svg__hello3_svg__cls-1" d="M32.4 145.83h266.03v1H32.4z"/>
    </svg>

As you can see, class names contains the name file duplicated different times (`hello3_svg__hello3_svg__hello3_svg__cls-1`).

[This PR](https://github.com/svg/svgo/pull/1135) should solve the problem.

**Comment by kylemh** [comment]
https://github.com/svg/svgo/pull/1227

Copied this PR, but removed the extra changes

**Comment by TrySound** [comment]
Fixed in 2.0.1

**Comment by kylemh** [comment]
@TrySound was excited to ditch my fork and come back to the fold, but I just tried using `svgo@2.0.3` and the following config:

```

**Comment by TrySound** [comment]
Hi! Configuration is changed in v2. See https://github.com/svg/svgo/releases/tag/v2.0.0

```js
const { extendDefaultPlugins } = require('svgo');
module.exports = {
  "plugins": extendDefaultPlugins([
    {
      name: "addAttributesToSVGElement",
      params: {
        "attributes": [{ "aria-hidden": "true" }]
      }
    },
    {
      name: "prefixIds",
      params: {
        "delim": "_"
      }
    },
    {
      name: "cleanupIDs", params: { "minify": true }
    },
    "cleanupListOfValues",
    "convertColors",
    "convertStyleToAttrs",
    "convertTransform",
    "mergePaths",
    "minifyStyles",
    "moveElemesAttrsToGroup",
    {
      name: "removeAttrs",
      params: { attrs: ["fill-rule", "fillRule"] }
    },
    "removeComments",
    { name: "removeDesc", params: { removeAny: true } },
    "removeDimensions",
    "removeDoctype",
    "removeEditorsNSData",
    "removeEmptyAttrs",
    "removeEmptyContainers",
    "removeEmptyText",
    "removeNonInheritableGroupAttrs",
    "removeTitle",
    "removeUnknownsAndDefaults",
    "removeUnusedNS",
    "removeUselessDefs",
    "removeUselessStrokeAndFill",
    "removeXMLProcInst",
    "sortAttrs",
  ]),
  "floatPrecision": 3,
  "multipass": true
}
```

**Comment by kylemh** [comment]
Great catch! Adjusted accordingly, but ran into #1358

**Comment by kylemh** [comment]
Circling back... I forced the version of SVGO to v2 via `resolutions` key in `package.json` to confirm SVGO CLI behavior.

Unfortunately, I'm still seeing classnames continuing to be edited on each SVGO CLI command.

## Proof there's only SVGOv2: 
<img width="1102" alt="Screen Shot 2021-02-21 at 12 00 11 PM" src="https://user-images.githubusercontent.com/9523719/108636790-7386b580-743c-11eb-8a23-f782d97ebda0.png">

## Beginning:
<img width="937" alt="Screen Shot 2021-02-21 at 12 00 22 PM" src="https://user-images.githubusercontent.com/9523719/108636808-85685880-743c-11eb-8650-362c6a31e177.png">

## After 1st `yarn svgo --pretty --config=svgo.config.format.js ./svgs/GoogleDrive.svg` 
<img width="1118" alt="Screen Shot 2021-02-21 at 12 00 33 PM" src="https://user-images.githubusercontent.com/9523719/108636801-7e414a80-743c-11eb-8302-b7f09544e0ba.png">

## After 2nd `yarn svgo --pretty --config=svgo.config.format.js ./svgs/GoogleDrive.svg` 
<img width="1226" alt="Screen Shot 2021-02-21 at 12 00 38 PM" src="https://user-images.githubusercontent.com/9523719/108636828-af217f80-743c-11eb-9ae2-49a0de1f2e26.png">

**Comment by TrySound** [comment]
I see. Well, this is expected behaviour. If you want to have better optimized svg use `--multipass` flag. Otherwise run svgo only once per svg.

**Comment by kylemh** [comment]
Is there anything against merging a PR like #1135 which prevents prepending class name if it's already added?

**Comment by TrySound** [comment]
It may be unreliable in case if prefix matches actual id.

**Comment by kylemh** [comment]
What about checking for that situation?

I'm surprised classes get prefixed when `prefixIds` I think would only be for the value of the `id` attribute?

**Comment by TrySound** [comment]
I agree naming is not very reliable. Though there is an option to disable or id or classnames prefixing
```
    delim: '__',
    prefixIds: true,
    prefixClassNames: true,
```
